# Site settings
title: Sutan's Lab
description: A blog and journal about Sutan Nst, Junior Developer
baseurl: "" # the subpath of your site
url: "https://sutanlab.js.org" # the base hostname & protocol for your site

# User settings
username: Sutan Nst.
user_description: Learner, Coder, Coffee Maniac
user_title: sgnzst
email: sutan.gnst@gmail.com
github_username:  sgnzst
medium_username: sutan.gnst
facebook_username:  sgnzst
instagram_username: sutan_gnst
disqus_username: sutanlab
gplus_username: u/0/112138172681575865281
twitter_username: none

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 5
paginate_path: /page/:num

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: Projects
    url: /projects
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# my collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# plugins
plugins: [jekyll-paginate]

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', '_drafts']
